In [13]:
import pandas as pd
df=pd.read_csv("coffe_sales.csv")
df.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,NaN,card,38.7,Latte,Morning,Fri,Mar,5,3,3/1/2024,15:50.5
1,12.0,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,3/1/2024,19:22.5
2,12.0,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,3/1/2024,20:18.1
3,13.0,card,28.9,Americano,Afternoon,Fri,Mar,5,3,3/1/2024,46:33.0
4,13.0,card,38.7,Latte,Afternoon,Fri,Mar,5,3,3/1/2024,48:14.6

In [14]:
df.describe()

       hour_of_day        money  Weekdaysort    Monthsort
count  3546.000000  3547.000000  3547.000000  3547.000000
mean     14.186971    31.645216     3.845785     6.453905
std       4.234023     4.877754     1.971501     3.500754
min       6.000000    18.120000     1.000000     1.000000
25%      10.000000    27.920000     2.000000     3.000000
50%      14.000000    32.820000     4.000000     7.000000
75%      18.000000    35.760000     6.000000    10.000000
max      22.000000    38.700000     7.000000    12.000000

In [15]:
df.dtypes

hour_of_day    float64
cash_type       object
money          float64
coffee_name     object
Time_of_Day     object
Weekday         object
Month_name      object
Weekdaysort      int64
Monthsort        int64
Date            object
Time            object
dtype: object

In [16]:
#Handling missing values
df.isnull().sum()

hour_of_day    1
cash_type      0
money          0
coffee_name    0
Time_of_Day    0
Weekday        0
Month_name     0
Weekdaysort    0
Monthsort      0
Date           0
Time           0
dtype: int64

In [17]:
#Filling msiising values with the mean of the column
df['hour_of_day_fillNA']=df['hour_of_day'].fillna(df['hour_of_day'].mean())
df

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time,hour_of_day_fillNA
0,NaN,card,38.70,Latte,Morning,Fri,Mar,5,3,3/1/2024,15:50.5,14.186971
1,12.0,card,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3,3/1/2024,19:22.5,12.000000
2,12.0,card,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3,3/1/2024,20:18.1,12.000000
3,13.0,card,28.90,Americano,Afternoon,Fri,Mar,5,3,3/1/2024,46:33.0,13.000000
4,13.0,card,38.70,Latte,Afternoon,Fri,Mar,5,3,3/1/2024,48:14.6,13.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
3542,10.0,card,35.76,Cappuccino,Morning,Sun,Mar,7,3,3/23/2025,34:54.9,10.000000
3543,14.0,card,35.76,Cocoa,Afternoon,Sun,Mar,7,3,3/23/2025,43:37.4,14.000000
3544,14.0,card,35.76,Cocoa,Afternoon,Sun,Mar,7,3,3/23/2025,44:16.9,14.000000
3545,15.0,card,25.96,Americano,Afternoon,Sun,Mar,7,3,3/23/2025,47:28.7,15.000000
3546,18.0,card,35.76,Latte,Night,Sun,Mar,7,3,3/23/2025,11:38.6,18.000000

In [18]:
#Change the datatype
#convert categorical data into numerical data
df.dtypes

hour_of_day           float64
cash_type              object
money                 float64
coffee_name            object
Time_of_Day            object
Weekday                object
Month_name             object
Weekdaysort             int64
Monthsort               int64
Date                   object
Time                   object
hour_of_day_fillNA    float64
dtype: object

In [20]:
#Renaming columns
df=df.rename(columns={'hour_of_day':'hour'})
df.head()

,hour,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time,hour_of_day_fillNA
0,NaN,card,38.7,Latte,Morning,Fri,Mar,5,3,3/1/2024,15:50.5,14.186971
1,12.0,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,3/1/2024,19:22.5,12.000000
2,12.0,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,3/1/2024,20:18.1,12.000000
3,13.0,card,28.9,Americano,Afternoon,Fri,Mar,5,3,3/1/2024,46:33.0,13.000000
4,13.0,card,38.7,Latte,Afternoon,Fri,Mar,5,3,3/1/2024,48:14.6,13.000000

In [22]:
#Change the datatype
df['money_new']=df['money'].astype(int)
df

,hour,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time,hour_of_day_fillNA,money_new
0,NaN,card,38.70,Latte,Morning,Fri,Mar,5,3,3/1/2024,15:50.5,14.186971,38
1,12.0,card,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3,3/1/2024,19:22.5,12.000000,38
2,12.0,card,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3,3/1/2024,20:18.1,12.000000,38
3,13.0,card,28.90,Americano,Afternoon,Fri,Mar,5,3,3/1/2024,46:33.0,13.000000,28
4,13.0,card,38.70,Latte,Afternoon,Fri,Mar,5,3,3/1/2024,48:14.6,13.000000,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3542,10.0,card,35.76,Cappuccino,Morning,Sun,Mar,7,3,3/23/2025,34:54.9,10.000000,35
3543,14.0,card,35.76,Cocoa,Afternoon,Sun,Mar,7,3,3/23/2025,43:37.4,14.000000,35
3544,14.0,card,35.76,Cocoa,Afternoon,Sun,Mar,7,3,3/23/2025,44:16.9,14.000000,35
3545,15.0,card,25.96,Americano,Afternoon,Sun,Mar,7,3,3/23/2025,47:28.7,15.000000,25
3546,18.0,card,35.76,Latte,Night,Sun,Mar,7,3,3/23/2025,11:38.6,18.000000,35

In [23]:
df['new_money_value']=df['money'].apply(lambda x:x*2)
df.head()

,hour,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time,hour_of_day_fillNA,money_new,new_money_value
0,NaN,card,38.7,Latte,Morning,Fri,Mar,5,3,3/1/2024,15:50.5,14.186971,38,77.4
1,12.0,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,3/1/2024,19:22.5,12.000000,38,77.4
2,12.0,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,3/1/2024,20:18.1,12.000000,38,77.4
3,13.0,card,28.9,Americano,Afternoon,Fri,Mar,5,3,3/1/2024,46:33.0,13.000000,28,57.8
4,13.0,card,38.7,Latte,Afternoon,Fri,Mar,5,3,3/1/2024,48:14.6,13.000000,38,77.4

In [26]:
#Data agrregating and grouping
grouped_mean=df.groupby('coffee_name')['hour_of_day_fillNA'].median()
print(grouped_mean)

coffee_name
Americano              13.0
Americano with Milk    13.0
Cappuccino             15.0
Cocoa                  16.0
Cortado                12.0
Espresso               14.0
Hot Chocolate          17.0
Latte                  15.0
Name: hour_of_day_fillNA, dtype: float64

In [30]:
df.groupby(['coffee_name','Time_of_Day'])['hour_of_day_fillNA'].median()

coffee_name          Time_of_Day
Americano            Afternoon      14.0
                     Morning        10.0
                     Night          18.0
Americano with Milk  Afternoon      14.0
                     Morning        10.0
                     Night          19.0
Cappuccino           Afternoon      14.0
                     Morning         9.0
                     Night          19.0
Cocoa                Afternoon      14.0
                     Morning         9.0
                     Night          19.0
Cortado              Afternoon      13.5
                     Morning         9.0
                     Night          19.0
Espresso             Afternoon      14.0
                     Morning        10.0
                     Night          18.0
Hot Chocolate        Afternoon      15.0
                     Morning        10.0
                     Night          19.0
Latte                Afternoon      15.0
                     Morning         9.0
                     Night          19.0
Name: hour_of_day_fillNA, dtype: float64

In [31]:
#Aggregate multiple functions
df.groupby(['coffee_name','Time_of_Day'])['hour_of_day_fillNA'].agg(['mean','count','median'])

                                      mean  count  median
coffee_name         Time_of_Day
Americano           Afternoon    13.901288    233    14.0
                    Morning       9.561644    219    10.0
                    Night        18.785714    112    18.0
Americano with Milk Afternoon    13.820084    239    14.0
                    Morning       9.416918    331    10.0
                    Night        19.238494    239    19.0
Cappuccino          Afternoon    14.115854    164    14.0
                    Morning       9.155738    122     9.0
                    Night        19.095000    200    19.0
Cocoa               Afternoon    14.253333     75    14.0
                    Morning       9.293103     58     9.0
                    Night        19.235849    106    19.0
Cortado             Afternoon    13.784091     88    13.5
                    Morning       9.391608    143     9.0
                    Night        19.196429     56    19.0
Espresso            Afternoon    14.107143     56    14.0
                    Morning       9.727273     44    10.0
                    Night        18.517241     29    18.0
Hot Chocolate       Afternoon    14.637500     80    15.0
                    Morning       9.979592     49    10.0
                    Night        19.353741    147    19.0
Latte               Afternoon    14.277778    270    15.0
                    Morning       9.182265    215     9.0
                    Night        19.294118    272    19.0