In [ ]:
""""
used in data analysis and data cleaning
provides tow primary data structures :series and DataFrame
serie-one dimensional array
DataFrame-two dimensional array,size-mutable and potentially heterogenous tabular DS with rows and columns

"""

In [ ]:
#Series

In [1]:

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n ",series)
print(type(series))

Series
  0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
#Creating series from dictionary elemnts
data={"a":1,"b":2,"c":3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [6]:
#DataFrame -two dimensional
#Create dataframe form a dictionary of list
data={
    "Name":["Joy","Mercy","Neno"],
    "Age":[25,30,23],
    "City":["Nairobi","New York","Mombasa"]
}
df=pd.DataFrame(data)
print(df)

    Name  Age      City
0    Joy   25   Nairobi
1  Mercy   30  New York
2   Neno   23   Mombasa

In [7]:
import numpy as np
np.array(df)

array([['Joy', 25, 'Nairobi'],
       ['Mercy', 30, 'New York'],
       ['Neno', 23, 'Mombasa']], dtype=object)

In [8]:
#Create dtframe form a list of dictionaries
data=[
    {"Name":"Faith","Age":20,"City":"Nairobi"},
    {"Name":"Joy","Age":22,"City":"Newyork"},
    {"Name":"Fien","Age":24,"City":"Momabsa"},
    {"Name":"Liv","Age":23,"City":"Kisumu"}
]
df=pd.DataFrame(data)
print(df)

    Name  Age     City
0  Faith   20  Nairobi
1    Joy   22  Newyork
2   Fien   24  Momabsa
3    Liv   23   Kisumu

In [9]:
#Accessing dtaa form dataframe
df

    Name  Age     City
0  Faith   20  Nairobi
1    Joy   22  Newyork
2   Fien   24  Momabsa
3    Liv   23   Kisumu

In [10]:
df["Name"]

0    Faith
1      Joy
2     Fien
3      Liv
Name: Name, dtype: object

In [11]:
df.loc[0]

Name      Faith
Age          20
City    Nairobi
Name: 0, dtype: object

In [16]:
df.loc[0][0]

C:\Users\faith\AppData\Local\Temp\ipykernel_2172\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Faith'

In [19]:
#Accessing a specified element
df.at[1,'Name']

'Joy'

In [20]:
#Accessing specified elemnt using iat
df.iat[2,2]

'Momabsa'

In [24]:
#Data manipulation with dataframes
df['Salary']=[5000,4000,4500,5300]
df

    Name  Age     City  Salary
0  Faith   20  Nairobi    5000
1    Joy   22  Newyork    4000
2   Fien   24  Momabsa    4500
3    Liv   23   Kisumu    5300

In [26]:
#Removing a column
df.drop('Salary',axis=1,inplace=True)

In [29]:
#Add age to the column
df['Age']=df['Age']+1
df

    Name  Age     City
0  Faith   23  Nairobi
1    Joy   25  Newyork
2   Fien   27  Momabsa
3    Liv   26   Kisumu

In [6]:
#Merging and joining DataFrames
import pandas as pd
df1=pd.DataFrame({'key':['A','B','C'], 'value1':[1,2,3]})
df2=pd.DataFrame({'key':['A','B','D'], 'value2':[4,5,6]})

In [7]:
df1

  key  value1
0   A       1
1   B       2
2   C       3

In [8]:
df2

  key  value2
0   A       4
1   B       5
2   D       6

In [9]:
#Merge the dataframes on the key columns
pd.merge(df1,df2,on='key',how='inner')

  key  value1  value2
0   A       1       4
1   B       2       5

In [10]:
pd.merge(df1,df2,on='key',how='outer')

  key  value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [11]:
pd.merge(df1,df2,on='key',how='left')

  key  value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [12]:
pd.merge(df1,df2,on='key',how='right')

  key  value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [15]:

!pip install BeautifulSoup4

Collecting BeautifulSoup4
  Downloading beautifulsoup4-4.14.2-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>1.2 (from BeautifulSoup4)
  Using cached soupsieve-2.8-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from BeautifulSoup4)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading beautifulsoup4-4.14.2-py3-none-any.whl (106 kB)
Using cached soupsieve-2.8-py3-none-any.whl (36 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, soupsieve, BeautifulSoup4

   ---------------------------------------- 0/3 [typing-extensions]
   ---------------------------------------- 0/3 [typing-extensions]
   ------------- -------------------------- 1/3 [soupsieve]
   ------------- -------------------------- 1/3 [soupsieve]
   ------------- -------------------------- 1/3 [soupsieve]
   -------------------------- ------------- 2/3 [BeautifulSoup4]
   -------------------------- ------------- 2/3 [BeautifulSoup4]
   -------------------------- ------------- 2/3 [BeautifulSoup4]
   -------------------------- ------------- 2/3 [BeautifulSoup4]
   -------------------------- ------------- 2/3 [BeautifulSoup4]
   -------------------------- ------------- 2/3 [BeautifulSoup4]
   -------------------------- ------------- 2/3 [BeautifulSoup4]
   -------------------------- ------------- 2/3 [BeautifulSoup4]
   ---------------------------------------- 3/3 [BeautifulSoup4]

Successfully installed BeautifulSoup4-4.14.2 soupsieve-2.8 typing-extensions-4.15.0

In [16]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B4B570AAB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl.metadata
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl.metadata